[platformio]
default_envs = blackpill_f411ce

[env:blackpill_f411ce]
platform = ststm32
board = blackpill_f411ce
framework = cmsis

upload_protocol = dfu

lib_deps =
    https://github.com/hathach/tinyusb.git#0.21.0

lib_ldf_mode = deep+

build_flags =
    -Iinclude
    '-DCFG_TUSB_CONFIG_FILE="tusb_config.h"'
    -DSTM32F411xE
    -DHSE_VALUE=25000000U
    -O2

monitor_speed = 115200
monitor_dtr = 1
monitor_rts = 0
monitor_echo = yes
monitor_eol = CRLF
